# Generated by Django 5.2 on 2025-05-22 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestamo',
            name='devuelto',
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='rut',
            field=models.CharField(max_length=12),
        ),
    ]
