# Generated by Django 5.2.1 on 2025-06-06 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0002_remove_prestamo_devuelto_alter_prestamo_rut'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prestamo',
            options={'ordering': ['-fecha_prestamo'], 'verbose_name': 'Préstamo', 'verbose_name_plural': 'Préstamos'},
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='celular',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='curso',
            field=models.CharField(choices=[('1_basico', '1º Básico'), ('2_basico', '2º Básico'), ('3_basico', '3º Básico'), ('4_basico', '4º Básico'), ('5_basico', '5º Básico'), ('6_basico', '6º Básico'), ('7_basico', '7º Básico'), ('8_basico', '8º Básico'), ('1_medio', '1º Medio'), ('2_medio', '2º Medio'), ('3_medio', '3º Medio'), ('4_medio', '4º Medio'), ('otro', 'Otro / No Aplica')], default='otro', max_length=20),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='nombre_persona',
            field=models.CharField(max_length=100),
        ),
    ]
