# Generated by Django 5.2 on 2025-06-09 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0002_remove_prestamo_devuelto_alter_prestamo_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='curso',
            field=models.CharField(choices=[('1_BASICO', '1° Básico'), ('2_BASICO', '2° Básico'), ('3_BASICO', '3° Básico'), ('4_BASICO', '4° Básico'), ('5_BASICO', '5° Básico'), ('6_BASICO', '6° Básico'), ('7_BASICO', '7° Básico'), ('8_BASICO', '8° Básico'), ('1_MEDIO', '1° Medio'), ('2_MEDIO', '2° Medio'), ('3_MEDIO', '3° Medio'), ('4_MEDIO', '4° Medio'), ('PROFESOR', 'Profesor'), ('ADMINISTRATIVO', 'Administrativo'), ('OTROS', 'Otros')], default='OTROS', max_length=50),
        ),
    ]
