# Generated by Django 5.2.1 on 2025-06-08 22:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0003_alter_prestamo_options_alter_prestamo_celular_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prestamo',
            options={},
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='celular',
            field=models.CharField(default=django.utils.timezone.now, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='curso',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='nombre_persona',
            field=models.CharField(max_length=200),
        ),
    ]
