# Generated by Django 5.2 on 2025-06-09 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0003_alter_prestamo_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='curso',
            field=models.CharField(choices=[('1A', '1° A'), ('1B', '1° B'), ('1C', '1° C'), ('1D', '1° D'), ('1E', '1° E'), ('1F', '1° F'), ('1G', '1° G'), ('2A', '2° A'), ('2B', '2° B'), ('2C', '2° C'), ('2D', '2° D'), ('2E', '2° E'), ('2F', '2° F'), ('2G', '2° G'), ('3HC', '3° H.C.'), ('4HC', '4° H.C.'), ('3CM', '3° Construcciones Metálicas'), ('4CM', '4° Construcciones Metálicas'), ('3MI', '3° Mecánica Industrial'), ('4MI', '4° Mecánica Industrial'), ('3EL', '3° Electricidad'), ('4EL', '4° Electricidad'), ('3ELE', '3° Electrónica'), ('4ELE', '4° Electrónica'), ('3ENF', '3° Enfermería'), ('4ENF', '4° Enfermería'), ('3GAS', '3° Gastronomía'), ('4GAS', '4° Gastronomía'), ('3EDI', '3° Edificación'), ('4EDI', '4° Edificación'), ('TALLER_1', 'Taller Laboral 1'), ('TALLER_2', 'Taller Laboral 2'), ('FUNCIONARIO', 'Funcionario')], default='OTROS', max_length=50),
        ),
    ]
