# Generated by Django 5.2 on 2025-04-21 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=200)),
                ('genero', models.CharField(max_length=50)),
                ('disponibilidad', models.BooleanField(default=True)),
                ('stock', models.IntegerField(default=1)),
            ],
        ),
    ]
