# Generated by Django 5.2 on 2025-05-27 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0004_usuario_perfilusuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='disponibilidad',
        ),
    ]
