# Generated by Django 5.2 on 2025-05-27 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0005_remove_libro_disponibilidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='portada',
        ),
        migrations.AddField(
            model_name='libro',
            name='portada_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL de la Portada del libro'),
        ),
    ]
